In [1]:
import numpy as np
np.array(['a','b','c','d','e'],ndmin=2)

array([['a', 'b', 'c', 'd', 'e']], dtype='<U1')

In [3]:
 np.array([['a','b'],['c','d','e']])<span style="background-color: #fafafa;color: #333333;font-family: Verdana, Geneva, sans-serif;font-size: 16px;font-weight:inherit"> </span>

SyntaxError: invalid syntax (<ipython-input-3-f5b13cf55eff>, line 1)

In [4]:
 np.array(['a','b','c','d','e'],ndmin=1)<span style="background-color: #fafafa;color: #333333;font-family: Verdana, Geneva, sans-serif;font-size: 16px;font-weight: inherit"> </span>

SyntaxError: invalid syntax (<ipython-input-4-59c7054e8439>, line 1)

In [5]:
a=np.array(['a','b',2,'3.0'])
a

array(['a', 'b', '2', '3.0'], dtype='<U3')

In [8]:
type(a)

numpy.ndarray

In [9]:
a.ndim

1

In [10]:
a.shape

(4,)

In [11]:
a.size

4

In [12]:
a.dtype

dtype('<U3')

In [13]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b.flatten()

array([1, 2, 3, 4, 5, 6])

In [15]:
 b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
b[:2,::2]

array([[1, 3],
       [4, 6]])

In [17]:
b-4

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [18]:
b.sum()

21

In [19]:
b-2*b

array([[-1, -2, -3],
       [-4, -5, -6]])

In [20]:
np.sort(np.array([[3,2,1],[5,2,4]]))

array([[1, 2, 3],
       [2, 4, 5]])

In [21]:
import pandas as pd
data={'Element':['Silver','Gold','Platinum','Copper'],'Atomic Number':[47,79,78,29]}
frame=pd.DataFrame(data,index=['element 1','element 2','element 3','element 4'])
frame

Element  Atomic Number
element 1    Silver             47
element 2      Gold             79
element 3  Platinum             78
element 4    Copper             29

In [22]:
data={'Red':pd.DataFrame(np.random.randn(4,2)),
  'Blue':pd.DataFrame(np.random.randn(4,3))}
pd.Panel(data)

C:\Users\Juhi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3325: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: Red to Blue
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2

In [25]:
data=np.array([1,2,3,3,4])
pd.Series(data)

0    1
1    2
2    3
3    3
4    4
dtype: int32

In [26]:
pd.Series(np.array(['a','c','b']))

0    a
1    c
2    b
dtype: object

In [27]:
frame.iloc[0:2,:]

Element  Atomic Number
element 1  Silver             47
element 2    Gold             79

In [28]:
frame.describe()

Atomic Number
count       4.000000
mean       58.250000
std        24.513602
min        29.000000
25%        42.500000
50%        62.500000
75%        78.250000
max        79.000000

In [29]:
frame.rank()

Element  Atomic Number
element 1      4.0            2.0
element 2      2.0            4.0
element 3      3.0            3.0
element 4      1.0            1.0

In [30]:
frame=pd.DataFrame(np.random.randn(4,3),index=[1,2,4,7],columns=['A','B','C'])
frame.reindex([1,2,3,4,5,6,7])

A         B         C
1 -0.075408 -0.410281  1.328531
2  0.285399 -0.640926  2.200077
3       NaN       NaN       NaN
4 -0.480270  0.327538  0.695472
5       NaN       NaN       NaN
6       NaN       NaN       NaN
7 -0.551370  0.271678  1.528163

In [31]:
frame=frame.reindex([1,2,3,4,5,6,7])
frame['B'].isnull()

1    False
2    False
3     True
4    False
5     True
6     True
7    False
Name: B, dtype: bool

In [32]:
frame.dropna()

A         B         C
1 -0.075408 -0.410281  1.328531
2  0.285399 -0.640926  2.200077
4 -0.480270  0.327538  0.695472
7 -0.551370  0.271678  1.528163

In [33]:
from numpy import NaN
frame.replace({NaN:0.00})

A         B         C
1 -0.075408 -0.410281  1.328531
2  0.285399 -0.640926  2.200077
3  0.000000  0.000000  0.000000
4 -0.480270  0.327538  0.695472
5  0.000000  0.000000  0.000000
6  0.000000  0.000000  0.000000
7 -0.551370  0.271678  1.528163

In [34]:
frame.fillna(7)

A         B         C
1 -0.075408 -0.410281  1.328531
2  0.285399 -0.640926  2.200077
3  7.000000  7.000000  7.000000
4 -0.480270  0.327538  0.695472
5  7.000000  7.000000  7.000000
6  7.000000  7.000000  7.000000
7 -0.551370  0.271678  1.528163

In [35]:
frame.fillna(method='pad')

A         B         C
1 -0.075408 -0.410281  1.328531
2  0.285399 -0.640926  2.200077
3  0.285399 -0.640926  2.200077
4 -0.480270  0.327538  0.695472
5 -0.480270  0.327538  0.695472
6 -0.480270  0.327538  0.695472
7 -0.551370  0.271678  1.528163

In [36]:
frame.fillna(method='backfill')

A         B         C
1 -0.075408 -0.410281  1.328531
2  0.285399 -0.640926  2.200077
3 -0.480270  0.327538  0.695472
4 -0.480270  0.327538  0.695472
5 -0.551370  0.271678  1.528163
6 -0.551370  0.271678  1.528163
7 -0.551370  0.271678  1.528163

In [37]:
data={'Element':['Silver','Gold','Platinum','Copper'],'Atomic Number':[47,79,78,29]}
frame=pd.DataFrame(data,index=['element 1','element 2','element 3','element 4'])
frame

Element  Atomic Number
element 1    Silver             47
element 2      Gold             79
element 3  Platinum             78
element 4    Copper             29

In [38]:
 frame.head()

Element  Atomic Number
element 1    Silver             47
element 2      Gold             79
element 3  Platinum             78
element 4    Copper             29

In [39]:
frame.tail(3)

Element  Atomic Number
element 2      Gold             79
element 3  Platinum             78
element 4    Copper             29

In [40]:
frame.rename(columns={'Atomic Number':'Number','Element':'Name'},inplace=True)
frame

Name  Number
element 1    Silver      47
element 2      Gold      79
element 3  Platinum      78
element 4    Copper      29